/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Drivers/Inc/STM32F40xx.h"
#include "../Drivers/Inc/Stm324Fxx_GPIO_Interface.h"

int main(void)
{
GPIO_Handle_t EStopBtn, RestartBtn, MotorPin1, MotorPin2;
GPIOA_PClk_EN();

EStopBtn.ptr_GPIOxr = GPIOA;
EStopBtn.GPIO_PinConfig.PinNum = 0;
EStopBtn.GPIO_PinConfig.Mode = GPIO_MODE_IT_FT;
EStopBtn.GPIO_PinConfig.PullUp_PullDown = Pull_down;
EStopBtn.GPIO_PinConfig.Speed = High_speed;
GPIO_Init(&EStopBtn);


MotorPin1.ptr_GPIOxr = GPIOA;
MotorPin1.GPIO_PinConfig.PinNum = 1;
MotorPin1.GPIO_PinConfig.Mode = GPIO_MODE_Output;
MotorPin1.GPIO_PinConfig.OutputType = GPIO_OP_Type_PushPull;
MotorPin1.GPIO_PinConfig.Speed = High_speed;
GPIO_Init(&MotorPin1);

MotorPin2.ptr_GPIOxr = GPIOA;
MotorPin2.GPIO_PinConfig.PinNum = 2;
MotorPin2.GPIO_PinConfig.Mode = GPIO_MODE_Output;
MotorPin2.GPIO_PinConfig.OutputType = GPIO_OP_Type_PushPull;
MotorPin2.GPIO_PinConfig.Speed = High_speed;
GPIO_Init(&MotorPin2);

RestartBtn.ptr_GPIOxr = GPIOA;
RestartBtn.GPIO_PinConfig.PinNum = 3;
RestartBtn.GPIO_PinConfig.Mode = GPIO_MODE_IT_FT;
RestartBtn.GPIO_PinConfig.PullUp_PullDown = Pull_down;
RestartBtn.GPIO_PinConfig.Speed = High_speed;
GPIO_Init(&RestartBtn);

GPIO_IRQConfig_EN_DIS(IRQ_NO_EXTI_0,Enable);
GPIO_IRQConfig_EN_DIS(IRQ_NO_EXTI_3,Enable);
while (1)
{

}


}

void EXTI0_IRQHandler()
{
    GPIO_IRQHandling(0);
}
void EXTI3_IRQHandler()
{
    GPIO_IRQHandling(3);
}